### PR TITLE
Support `kalm_config` GKE addons

### PR DESCRIPTION
**Pull request by anhdle14**
* Adding config keys for kalm_config on resource_container_cluster.
* Adding schema for kalm_config on resource_container_cluster.

Reference APIs: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.KalmConfig

### CODE REVIEW

**Comment by anhdle14** [comment]
I have updated the test to `/google-beta/resource_container_cluster.go`.

**Comment by iangelov** [comment]
One passing comment - I wonder whether there's a typo in the test config, or whether it's supposed to fail?

I see 

```
    kaml_config {
      enabled = true
    }
```

repeated twice. I reckon it should be **kalm_config** instead of kaml_config?

**Comment by anhdle14** [comment]
> One passing comment - I wonder whether there's a typo in the test config, or whether it's supposed to fail?
> 
> I see
> 
> ```
>     kaml_config {
>       enabled = true
>     }
> ```
> 
> repeated twice. I reckon it should be **kalm_config** instead of kaml_config?

Sorry, the typo should be fixed now.

**Comment by ndmckinley** [comment]
Okay, thanks!  I'm running the tests on our end, will approve when they pass and merge upstream.  Can you resolve the conflicts?

**Comment by ndmckinley** [comment]
The test fails, seems like there's still a typo issue:

>     testing.go:635: Step 0 error: config is invalid: Unsupported block type: Blocks of type "kaml_config" are not expected here. Did you mean "kalm_config"?

**Comment by anhdle14** [comment]
> The test fails, seems like there's still a typo issue:
> 
> > ```
> > testing.go:635: Step 0 error: config is invalid: Unsupported block type: Blocks of type "kaml_config" are not expected here. Did you mean "kalm_config"?
> > ```

https://github.com/terraform-providers/terraform-provider-google-beta/commit/2a8a9e7b49589de776d8b67252ae227bb5b5e16c

I forced push for [this commit](https://github.com/terraform-providers/terraform-provider-google-beta/commit/2a8a9e7b49589de776d8b67252ae227bb5b5e16c) (because I was using --amend).

Sorry for the typos, I have also fix conflicts from the master.

**Comment by ndmckinley** [comment]
This test still fails.

>testing.go:635: Step 0 error: Argument or block definition required: On /opt/teamcity-agent/temp/buildTmp/tf-test096552936/main.tf line 29: An argument or block definition is required here.

Are you able to run the tests yourself?  That will make this faster - it's a manual step on our end so I only have time to run it a few times a day at the most.

**Comment by anhdle14** [comment]
Sorry, I missed a conflict, that would explain the error. I am able to run the test, is this [the guide](https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) to run the test locally?

**Comment by ndmckinley** [comment]
Yes, that will work!  Let me know when you've got the tests passing.  :)

**Comment by anhdle14** [comment]
Here are the tests running and PASS.

```bash
$ make testacc TEST=./google-beta TESTARGS='-run=testAccContainerCluster_withAddons'                -I-
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run=testAccContainerCluster_withAddons -timeout 240m -ldflags="-X=github.com/terraform-providers/terraform-provider-google-beta/version.ProviderVersion=acc"
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-google-beta/google-beta       1.077s [no tests to run]
make testacc TEST=./google-beta   10.04s user 2.24s system 211% cpu 5.810 total

$ make testacc TEST=./google-beta TESTARGS='-run=testAccContainerCluster_updateAddons'              -I-
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run=testAccContainerCluster_updateAddons -timeout 240m -ldflags="-X=github.com/terraform-providers/terraform-provider-google-beta/version.ProviderVersion=acc"
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-google-beta/google-beta       0.881s [no tests to run]
make testacc TEST=./google-beta   10.92s user 2.26s system 231% cpu 5.700 total
```

**Comment by ndmckinley** [comment]
Excellent, I'll go ahead and run them on our side then merge this upstream.  :)

**Comment by anhdle14** [comment]
Should I also update the documentation at [website/docs/r/container_cluster.html.markdown](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/website/docs/r/container_cluster.html.markdown)?

**Comment by ndmckinley** [comment]
Thank you, that would be helpful!

**Comment by anhdle14** [comment]
I think that is all

**Comment by ndmckinley** [comment]
Great, this is added!  It should be available in the next version of the provider.

**Pull request closed without merging**
