### PR TITLE
Documenting "address" attribute of compute_global_address

### PR DESCRIPTION
**Pull request by nickcarenza**

### CODE REVIEW

**Comment by slevenick** [comment]
Hey @nickcarenza thanks for the contribution.

This field is already documented in the `Argument Reference` section in this doc. You can see it here: https://www.terraform.io/docs/providers/google/r/compute_global_address.html

Generally the `Attributes Reference` section is for additional fields that are returned by the API but are not able to be set via the terraform config. Because of this I don't believe we should add this extra documentation.

**Comment by nickcarenza** [comment]
OK.

In https://www.terraform.io/docs/providers/google/r/compute_address.html address is listed as an attribute and an argument. I assumed it was because the argument is optional and when not provided is not known until the resource is created.

Are all arguments available as attributes?

**Comment by slevenick** [comment]
Odd, I wouldn't expect that to exist there.

I'll ask around.

You are correct that this argument is optional and not known until the resource is created, but I'm not sure why we would need to document it in the attributes section then. In general all arguments are available as attributes, but may not be specified if they are optional. (In this case `address` is optional as an input but always available as an attribute)

**Comment by slevenick** [comment]
Checked it out, it should only appear once. The fields presence in the `Attributes` section is implied by it being in the `Arguments` section. I'll remove the field from the docs for `compute_address`

Closing this out

**Pull request closed without merging**
