### PR TITLE
Feature/packet mirror forward rule

### PR DESCRIPTION
**Pull request by ferrier1**
Packet mirroring feature in GCP is in beta:
https://cloud.google.com/vpc/docs/packet-mirroring

The feature requires use of a TCP ILB which is enabled for packet mirroring.

This PR adds the option to create a forwarding rule with the mirroring option enabled.

### CODE REVIEW

**Comment by emilymye** [comment]
@ferrier1 Unfortunately this is one of our autogenerated resources, which means that we'll need to do this in https://github.com/GoogleCloudPlatform/magic-modules. A couple of options:

1. You can make changes in our autogeneration repo, Magic Modules - it would involve adding some straightforward YAML in [api.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/api.yaml), similar to very similar to `allowGlobalAccess`, minus the update URLs: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/api.yaml#L3324-L3329

The tests wouls go into the corresponding [test file](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/resource_compute_forwarding_rule_test.go.erb) but the field is beta-only so you'd need version gates around your test:
```
<% unless version == 'ga' -%>
...
<% end-%>

2. If you don't want to take on the task of compiling Magic Modules, I can try submitting your code and attempt to submit an upstream PR that will bring the changes up to MM without stomping over your commits too badly, but it's likely to do so since the autogeneration is whitespace-particular and whatnot. I'll try to get it out soon so you can at least look at it for an example if you want to go with option 1.

3. I can just do option 2 without merging in your PR - you wouldn't get contribution credit, but would also not have to do extra work.

**Comment by ferrier1** [comment]
Thanks for the reply. Ive just noteiced the magic modules note at the top of the page

Happy to make changes there instead

**Comment by emilymye** [comment]
hi @ferrier1 - sorry for the late reply! If you decide to make the changes in MM, @ me and I can review the PR. Thank you!

**Comment by ferrier1** [comment]
@emilymye Thanks for getting back to me. 
Here is the PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/3043

**Pull request closed without merging**
